package pe.com.sedapal.evaluacion.util;

public class DBConstants {
	public static final String PACKAGE_SISTEMA = "AEP_PKG_EVALUACION_COMPETENCIAS";
	public static final String SCHEMA_NAME = "EVACOM";
	
	//PROCEDURES
	public static final String PROCEDURE_OBTENER_GRUPO_COMPETENCIAS = "AEP_GRUPO_COMPETENCIA_LISTAR";
	public static final String PROCEDURE_INSERTAR_GRUPO_COMPETENCIAS = "AEP_GRUPO_COMPETENCIA_INSERTAR";
	public static final String PROCEDURE_EDITAR_GRUPO_COMPETENCIAS = "AEP_GRUPO_COMPETENCIA_EDITAR";
	
	public static final String PROCEDURE_OBTENER_COMPETENCIAS = "AEP_COMPETENCIA_LISTAR";
	public static final String PROCEDURE_INSERTAR_COMPETENCIAS = "AEP_COMPETENCIA_INSERTAR";
	public static final String PROCEDURE_EDITAR_COMPETENCIAS = "AEP_COMPETENCIA_EDITAR";
	public static final String PROCEDURE_CONSULTA_COMPETENCIAS = "AEP_COMPORTAMIENTO_CONSULTA";
	public static final String PROCEDURE_OBTENER_COMPETENCIAS_EVALUADO = "AEP_COMPETENCIA_EVALUADO_LISTAR";
	
	public static final String PROCEDURE_OBTENER_NIVEL= "AEP_NIVEL_LISTAR";
	public static final String PROCEDURE_INSERTAR_NIVEL= "AEP_NIVEL_INSERTAR";
	public static final String PROCEDURE_EDITAR_NIVEL= "AEP_NIVEL_EDITAR";
	
	public static final String PROCEDURE_OBTENER_COMPORTAMIENTO = "AEP_COMPORTAMIENTO_LISTAR";
	public static final String PROCEDURE_INSERTAR_COMPORTAMIENTO = "AEP_COMPORTAMIENTO_INSERTAR";
	public static final String PROCEDURE_EDITAR_COMPORTAMIENTO = "AEP_COMPORTAMIENTO_EDITAR";
	
	//CT-24042024-INICIO
	public static final String PROCEDURE_VALIDAR_ROL_ADMIN = "AEP_ROL_ADMIN_VALIDAR";
	//CT-24042024-FIN
	
	
	public static final String PROCEDURE_OBTENER_CALENDARIOS= "AEP_CALENDARIOS_VIGENTES";
	public static final String PROCEDURE_OBTENER_CALENDARIO= "AEP_CALENDARIO";
	public static final String PROCEDURE_OBTENER_CALENDARIO_PERMISOS= "AEP_CALENDARIO_PERMISOS";
	
	
	
	public static final String CONSTANTES_CORREO= "CORREO";
	public static final int  CONSTANTES_CORREO_REMITENTE_NOMBRE= 1;
	public static final int  CONSTANTES_CORREO_REMITENTE_CUENTA= 2;
	public static final int  CONSTANTES_CORREO_REMITENTE_PASSWORD= 3;
	public static final int  CONSTANTES_CORREO_URL= 4;
	
	public static final int  CONSTANTES_CORREO_ASUNTO_CONOCIMIENTO= 5;
	public static final int  CONSTANTES_CORREO_ASUNTO_AUTOEVALUACION= 6;
	public static final int  CONSTANTES_CORREO_ASUNTO_HECHOSRESALTANTES= 8;
	public static final int  CONSTANTES_CORREO_ASUNTO_EVALUACION= 9;
	public static final int  CONSTANTES_CORREO_ASUNTO_CALIBRACION= 14;
	public static final int  CONSTANTES_CORREO_ASUNTO_RETROALIMENTACION= 15;
	public static final int  CONSTANTES_CORREO_ASUNTO_PID= 16;
	public static final String CONSTANTES_CORREO_FORMATO_CONOCIMIENTO= "Conocimiento";
	public static final String CONSTANTES_CORREO_FORMATO_AUTOEVALUACION= "Autoevaluacion";
	public static final String CONSTANTES_CORREO_FORMATO_HECHORESALTANTE= "HechoResaltante";
	public static final String CONSTANTES_CORREO_FORMATO_EVALUACION= "Evaluacion";
	public static final String CONSTANTES_CORREO_FORMATO_CALIBRACION= "Calibracion";
	public static final String CONSTANTES_CORREO_FORMATO_RETROALIMENTACION= "Retroalimentacion";
	public static final String CONSTANTES_CORREO_FORMATO_PID = "Pid";
	
	public static final String CONSTANTES_URL_FOTOS= "FOTOS";
	
	
	//CONOCIMIENTO
	public static final String PROCEDURE_CONOCIMIENTO_COMPETENCIAS= "AEP_COMPETENCIAS_PUESTO";
	public static final String PROCEDURE_INSERTAR_CONOCIMIENTO = "AEP_CONOCIMIENTO_INSERTAR"; 
	
	
	//GRUPOS DE EVALUACION
	public static final String PROCEDURE_GRUPOS_EVALUACION= "AEP_GRUPOS_EVALUACION";
	public static final String PROCEDURE_GRUPO_EVALUACION= "AEP_GRUPO_EVALUACION";
	public static final String PROCEDURE_GRUPO_EVALUACION_UPDATE= "AEP_GRUPO_EVAL_UPDATE";
	public static final String PROCEDURE_GRUPO_EVALUACION_LISTA= "AEP_GRUPO_EVALUACION_LISTA";
	
	public static final String PROCEDURE_CORREO= "AEP_CORREO";
	public static final String PROCEDURE_CONSTANTE_LISTADO= "AEP_CONSTANTE_LISTADO";
	public static final String PROCEDURE_CONSTANTE_CONSULTA = "AEP_CONSTANTE_CONSULTA";
	public static final String PROCEDURE_CONSTANTE_GRABAR = "AEP_CONSTANTE_GRABAR";
	
	//AUTOEVALUACION
	public static final String PROCEDURE_AUTOEVALUACION_CONSULTA= "AEP_AUTOEVAL_CONSULTA";
	public static final String PROCEDURE_AUTOEVALUACION_COMPORTAMIENTOS= "AEP_AUTOEVAL_COMPORTAMIENTOS";
	public static final String PROCEDURE_AUTOEVALUACION_GRABAR= "AEP_AUTOEVAL_GRABAR";
	public static final String PROCEDURE_AUTOEVALUACION_GRABAR_FO= "AEP_AUTOEVAL_GRABAR_FO";
	
	//EVALUACION
	public static final String PROCEDURE_EVALUACION_LISTADO= "AEP_EVALUACION_LISTADO";
	public static final String PROCEDURE_EVALUACION_CONSULTA= "AEP_EVALUACION_CONSULTA";
	public static final String PROCEDURE_EVALUACION_CONSULTA180= "AEP_EVALUACION_CONSULTA180";
	public static final String PROCEDURE_EVALUACION_COMPORTAMIENTOS= "AEP_EVALUACION_COMPORTAMIENTOS";
	public static final String PROCEDURE_EVALUACION_GRABAR= "AEP_EVALUACION_GRABAR";
	public static final String PROCEDURE_EVALUACION_GRABAR_FO= "AEP_EVALUACION_GRABAR_FO";
	public static final String PROCEDURE_REPORTE_EVALUADORES= "AEP_EVALUACION_EVALUADORES";
	public static final String PROCEDURE_EVALUACION_NTERMINADOS= "AEP_EVALUADORES_TERMINADOS";
	public static final String PROCEDURE_EVALUACION_CONSOLIDADO90= "AEP_EVALUACION_CONSOLIDADO90";
	public static final String PROCEDURE_EVALUACION_CONSOLIDADO180= "AEP_EVALUACION_CONSOLIDADO180";
	
	//REPORTES
	public static final String PROCEDURE_REPORTE_CONOCIMIENTO= "AEP_CONOCIMIENTO_REPORTE";
	public static final String PROCEDURE_REPORTE_CONOCIMIENTO2= "AEP_CONOCIMIENTO_REPORTE2";
	public static final String PROCEDURE_REPORTE_GRUPO_EVALUACION= "AEP_GRUPO_EVAL_REPORTE";
	public static final String PROCEDURE_REPORTE_AUTOEVALUACION= "AEP_AUTOEVAL_REPORTE";
	public static final String PROCEDURE_REPORTE_AUTOEVALUACION2= "AEP_AUTOEVAL_REPORTE2";
	public static final String PROCEDURE_REPORTE_GLOBAL90= "AEP_GLOBAL90";
	
	//CONSTANTES DE CALENDARIO
	public static final String CONSTANT_CALENDAR_PARAMETRIZACION        = "PARAMETRIZACION";
	public static final String CONSTANT_CALENDAR_CONOCIMIENTO           = "CONOCIMIENTO";
	public static final String CONSTANT_CALENDAR_HECHOS_RELEVANTES      = "HECHOS_RELEVANTES";
	public static final String CONSTANT_CALENDAR_AUTOEVAL               = "AUTOEVAL";
	public static final String CONSTANT_CALENDAR_EVAL                   = "EVAL";
	public static final String CONSTANT_CALENDAR_CALIBRACION            = "CALIBRACION";
	public static final String CONSTANT_CALENDAR_RETROALIMENTACION      = "RETROALIMENTACION";
	public static final String CONSTANT_CALENDAR_PID_EST                = "PID_EST";
	public static final String CONSTANT_CALENDAR_PID_MON                = "PID_MON";
	public static final String CONSTANT_CALENDAR_PID_EVAL               = "PID_EVAL";
	public static final String CONSTANT_CALENDAR_REPORTES               = "REPORTES";


	public static final String PROCEDURE_HECHOSRESALTANTES_INSERT= "AEP_HECHOS_RESALT_INSERT";
	public static final String PROCEDURE_HECHOSRESALTANTES_CONSULTA= "AEP_HECHOS_RESALT_CONSULTA";
	
	//UPDATE DATA
	public static final String PROCEDURE_DIRECTORIO_INSERT= "AEP_DIRECTORIO_INSERT";
	public static final String PROCEDURE_DIRECTORIO_CONSULTA= "AEP_DIRECTORIO_CONSULTA";
	public static final String PROCEDURE_GERENCIA_INSERT= "AEP_GERENCIA_INSERT";
	public static final String PROCEDURE_EQUIPO_INSERT= "AEP_EQUIPO_INSERT";
	
	//RETROALIMENTACION
	public static final String PROCEDURE_RETROALIMENTACION_LISTADO= "AEP_RETROALIMENTACION_LISTADO";
	public static final String PROCEDURE_RETROALIMENTACION_EVALUADOR_GRABAR= "AEP_RETROAL_EVALUADOR_GRABAR";
	public static final String PROCEDURE_RETROALIMENTACION_EVALUADO_GRABAR= "AEP_RETROAL_EVALUADO_GRABAR";
	public static final String PROCEDURE_RETROALIMENTACION_CONSULTA= "AEP_RETROAL_CONSULTA";
	public static final String PROCEDURE_RETROALIMENTACION_TERMINADOS= "AEP_RETROAL_TERMINADOS";
	

	
	//CALIBRACION
	public static final String PROCEDURE_CALIBRACION_FICHA= "AEP_CALIBRACION_FICHA";
	public static final String PROCEDURE_CALIBRACION_REGISTRA= "AEP_CALIBRACION_REGISTRA";
	public static final String PROCEDURE_CALIBRACION_LISTA= "AEP_CALIBRACION_LISTA";
	public static final String PROCEDURE_CALIBRACION_EVALUADOR= "AEP_CALIBRACION_EVALUADOR";
	
	//PID
	public static final String PROCEDURE_PID_LISTADO= "AEP_PID_LISTADO";
	public static final String PROCEDURE_PID_CONSULTA= "AEP_PID_CONSULTA";
	public static final String PROCEDURE_PID_GRABAR= "AEP_PID_GRABAR";
	public static final String PROCEDURE_PID_DETALLE_GRABAR= "AEP_PID_DETALLE_GRABAR";
	public static final String PROCEDURE_PID_VEREDICTO_REGISTRO= "AEP_PID_VEREDICTO_REGISTRO";
	public static final String PROCEDURE_PID_VEREDICTO_CUMPLIMIENTO= "AEP_PID_VEREDICTO_CUMPLIMIENTO";
	public static final String PROCEDURE_PID_DET_ACTUALIZAR_RUTA_DOC = "AEP_PID_DET_ACTUALIZAR_RUTA_DOC";
	public static final String PROCEDURE_PID_REGISTRO_TERMINADOS= "AEP_PID_REGISTRO_TERMINADOS";
	public static final String PROCEDURE_PID_CUMPLIMIENTO_TERMINADOS= "AEP_PID_CUMPLIMIENTO_TERMINADOS";
	
	
	//REPORTES
	public static final String PROCEDURE_CORREO_EVALUADO_CONOCIMIENTO = "AEP_CORREO_EVALUADO_CONOCIMIENTO";
	public static final String PROCEDURE_CORREO_EVALUADO_AUTOEVALUACION = "AEP_CORREO_EVALUADO_AUTOEVALUACION";
	public static final String PROCEDURE_CORREO_EVALUADOR_EVALUACION = "AEP_CORREO_EVALUADOR_EVALUACION";
	public static final String PROCEDURE_CORREO_EVALUADO_RETROALIMENTACION = "AEP_CORREO_EVALUADO_RETROALIMENTACION";
	public static final String PROCEDURE_CORREO_EVALUADOR_RETROALIMENTACION = "AEP_CORREO_EVALUADOR_RETROALIMENTACION";
	public static final String PROCEDURE_CORREO_EVALUADO_PID_REGISTRO = "AEP_CORREO_EVALUADO_PID_REGISTRO";
	public static final String PROCEDURE_CORREO_EVALUADOR_PID_REGISTRO = "AEP_CORREO_EVALUADOR_PID_REGISTRO";
	public static final String PROCEDURE_CORREO_EVALUADO_PID_CUMPLIMIENTO = "AEP_CORREO_EVALUADO_PID_CUMPLIMIENTO";
	public static final String PROCEDURE_CORREO_EVALUADOR_PID_CUMPLIMIENTO = "AEP_CORREO_EVALUADOR_PID_CUMPLIMIENTO";


	
}
